CREATE TABLE IF NOT EXISTS personaje(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    imagen text NOT NULL CHECK (imagen <> ''),
    nombre text NOT NULL CHECK (nombre <> ''),
    edad integer NOT NULL,
    peso numeric NOT NULL,
    historia text NOT NULL,
    peliculasID integer[]
);

CREATE TABLE IF NOT EXISTS pelicula(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    imagen text NOT NULL CHECK (imagen <> ''),
    titulo text NOT NULL CHECK (titulo <> ''),
    fechaDeCreacion date NOT NULL,
    calificacion integer NOT NULL,
    personajeID integer[]
);

CREATE TABLE IF NOT EXISTS genero(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    imagen text NOT NULL CHECK (imagen <> ''),
    peliculasID integer[]
);